/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.KeyEvent;

/**
 *
 * @author mathe
 */
public class RemoveDDD extends javax.swing.JFrame {

    public RemoveDDD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaNumberWhithout = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNumbers = new javax.swing.JTextArea();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaNumberWhithout.setColumns(20);
        txaNumberWhithout.setRows(5);
        jScrollPane1.setViewportView(txaNumberWhithout);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 154, 268));

        txaNumbers.setColumns(20);
        txaNumbers.setRows(5);
        txaNumbers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txaNumbersKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txaNumbers);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 154, 268));

        lbl2.setText("jLabel1");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lbl1.setText("jLabel1");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txaNumbersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaNumbersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            String[] values = txaNumbers.getText().split("\n");
            int alter = 0;

            for (int i = 0; i < values.length; i++) {
//                            for (int i = values.length - 1; i > (-1); i--) {

//                if (values[i].trim().length() > 11) {
//                    alter++;
//                    values[i] = values[i].substring(2, values[i].length());
//                }
                    txaNumberWhithout.setText(txaNumberWhithout.getText() + "\n"+(i+1) +" "+values[i] );
            
            }

            lbl1.setText(values.length + " Numeros inseridos");
            lbl2.setText(alter + " Numeros Alterados");
        }
    }//GEN-LAST:event_txaNumbersKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveDDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveDDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveDDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveDDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveDDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextArea txaNumberWhithout;
    private javax.swing.JTextArea txaNumbers;
    // End of variables declaration//GEN-END:variables
}
